# Generated by Django 3.2.7 on 2021-09-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_m', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
    ]
