# Generated by Django 3.2.7 on 2021-09-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coche', '0004_alter_coche_precio'),
        ('cliente', '0002_alter_cliente_telefono'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='CLIENTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='VEHICULO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coche.coche'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(verbose_name='fecha de venta'),
        ),
    ]
