# Generated by Django 3.2.7 on 2021-09-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_nit_c'),
        ('venta', '0002_auto_20210929_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='CLIENTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='CLIENTE'),
        ),
    ]
