# Generated by Django 3.2.7 on 2021-09-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.IntegerField()),
                ('precio', models.BigIntegerField(max_length=20)),
                ('codigo_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marca.marca')),
            ],
        ),
    ]
