# Generated by Django 3.2.7 on 2021-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coche', '0003_alter_coche_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
